# Generated by Django 4.0.5 on 2022-06-12 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "serial_number",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("manufacturer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("departure_airport", models.CharField(max_length=200)),
                ("departure_timestamp", models.DateTimeField()),
                ("arrival_airport", models.CharField(max_length=200)),
                ("arrival_timestamp", models.DateTimeField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights",
                        to="api.aircraft",
                    ),
                ),
            ],
        ),
    ]
