# Generated by Django 4.0.5 on 2022-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="serial_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
